### ISSUE TITLE
Error after installing via control panel

### ISSUE THREAD

**Issue by arifje** [doublesecretagency/craft-upvote#1]
![screen shot 2018-05-08 at 19 29 31](https://user-images.githubusercontent.com/1286410/39772704-38f5e5e0-52f6-11e8-8760-3a725439a1ee.jpg)

**Comment by lindseydiloreto** [comment]
Interesting... Is this being installed fresh? Or upgraded from a previous version (via Craft 2)?

**Comment by arifje** [comment]
I installed a fresh Craft 3 beta version a few weeks ago, updated to latest versions.

Tried to install upvote some minutes ago via the control panel and got this error.

Also tried to install with composer on the CLI; install completes without errors, but when I access the plugin page in the CP I get another error;

![screen shot 2018-05-08 at 20 33 09](https://user-images.githubusercontent.com/1286410/39775782-30f1b488-52ff-11e8-8baa-778c758a5b0e.jpg)

**Comment by lindseydiloreto** [comment]
This is now fixed in 2.0.1. You may need to update via Composer if the CP is inaccessible.

Let me know if you're still getting the other error!

**Comment by arifje** [comment]
works, thanks!
