### ISSUE TITLE
Upvote "Fails" Over AJAX When Using Webhooks Plug-in

### ISSUE THREAD

**Issue by theskyfloor** [doublesecretagency/craft-upvote#11]
When I try to send a Webhook on the `afterVote` event the ajax javascript fails. Any ideas?

<img width="1680" alt="Screen Shot 2019-05-09 at 3 54 07 PM" src="https://user-images.githubusercontent.com/8887839/57486308-78807200-7273-11e9-8382-0c174da210b8.png">

**Comment by lindseydiloreto** [comment]
Hmm... Take a look at your "Network" tab, see what's actually being returned.

**Comment by theskyfloor** [comment]
Will do

**Comment by lindseydiloreto** [comment]
It's been 3 years, I'm gonna assume you got this one resolved. 😄
