### ISSUE TITLE
AJAX to get tally

### ISSUE THREAD

**Issue by LouisCuvelier** [doublesecretagency/craft-upvote#14]
Hi,

I would like to get tally of element with an AJAX request.
My code below doesn't work and it returns any error in the Chrome console.
I suppose the action url is wrong ? I used [this](https://www.doublesecretagency.com/plugins/upvote/docs/getting-vote-totals).

```twig
{% set csrfParam = craft.app.request.csrfParam %}
{% set csrfToken = craft.app.request.csrfToken %}

<script>
  (async function getVotes() {
    try {
      var data = {
        "id": "{{ entry.id }}",
        "action": "upvote/upvote_query/tally",
        ["{{ csrfParam }}"]: "{{ csrfToken }}"
      };

      const response = await fetch(
        '',
        {
          method: "POST",
          headers: {
            'Accept': 'application/json',
            'Content-Type': 'application/json'
          },
          body: JSON.stringify(data)
        }
      );

      const json = await response.json();
      console.log(json);
    } catch (error) {
      console.log(error);
    }
  })();
</script>
```

**Comment by lindseydiloreto** [comment]
Hi Louis,

There is no native Controller action for getting the tally. `upvote_query/tally` doesn't exist.

In a custom module, you can use the following Service method...

```php
Upvote::$plugin->upvote_query->tally($elementId)
```

Hope that helps!

**Comment by LouisCuvelier** [comment]
Houra, It's working ! Thanks you @lindseydiloreto 
Thank you too @khalwat for [Plugin Factory](https://pluginfactory.io/)
