### ISSUE TITLE
How to output multiple votes?

### ISSUE THREAD

**Issue by AntonioStudioUntitled** [doublesecretagency/craft-upvote#17]
Awesome plugin, thank you for making one.

I was trying to find a solution for this, but I couldn't find one. 

What is the best way to show results for each multiple votes?

<p>Was the hotel comfortable?</p>
{{ craft.upvote.upvote(hotel.id, 'comfortable') }}
{{ craft.upvote.downvote(hotel.id, 'comfortable') }}

<p>Was the hotel clean?</p>
{{ craft.upvote.upvote(hotel.id, 'clean') }}
{{ craft.upvote.downvote(hotel.id, 'clean') }}

<p>Was the hotel staff friendly?</p>
{{ craft.upvote.upvote(hotel.id, 'friendlyStaff') }}
{{ craft.upvote.downvote(hotel.id, 'friendlyStaff') }}

for example 

{{ craft.upvote.totalUpvotes(elementId) }} 

this shows normal votes, what's the best to show multiple votes?

**Comment by AntonioStudioUntitled** [comment]
I guess this is the way to output right? 
{{ craft.upvote.totalUpvotes(elementId, 'clean, 'container'') }}

**Comment by lindseydiloreto** [comment]
Yup, that's correct!

```twig
{{ craft.upvote.totalUpvotes(elementId, 'clean') }}
```

`container` is the default value of the third parameter, so you actually don't even need to specify it.

https://www.doublesecretagency.com/plugins/upvote/docs/control-the-output-format
