### ISSUE TITLE
Display voting history only for one vote group

### ISSUE THREAD

**Issue by piotrpog** [doublesecretagency/craft-upvote#21]
Upvote plugin allows for multiple voting groups

https://www.doublesecretagency.com/plugins/upvote/docs/multiple-voting-for-the-same-element

It would be useful if we could get user vote history only from one group - right now I need to extract  using array keys like these `'1383:like'`.

**Comment by lindseydiloreto** [comment]
That's interesting... Sounds like you're looking for a method which would effectively do that automatically.

From the perspective of "which group has votes", it's certainly a windy path to get the data that you need. I can see what you're saying, it would definitely be helpful to determine that information in a more streamlined way.

I don't think I'll be able to add anything along these lines soon, but this does align well with some longer-term plans that I have. I'll keep this FR on file until I get a chance to circle back and readdress it.

Thanks for the feedback! 👍

**Comment by lindseydiloreto** [comment]
I'm going to reasonably assume that you filed #22 with the same mentality. When I (eventually) put a formal solution in place, I'll make sure it satisfies that issue as well.

**Comment by lindseydiloreto** [comment]
This is now possible using the `userHistoryByKey` method...

```twig
{% set history = craft.upvote.userHistoryByKey(currentUser.id, 'yourKey') %}
```

https://www.doublesecretagency.com/plugins/upvote/docs/user-vote-history

If you pass a `keyFilter` into that method, it will only return a subset of the history. If you omit the `keyFilter`, it will return the entire vote history as a group of subsets.

Thanks for submitting the FR!
