### ISSUE TITLE
Method for showing if element was voted on by specific user

### ISSUE THREAD

**Issue by piotrpog** [doublesecretagency/craft-upvote#22]
It would be useful for wishlist/favlist functionality.

**Comment by lindseydiloreto** [comment]
If you start with the User, you can find out all of the elements that [they have voted on...](https://www.doublesecretagency.com/plugins/upvote/docs/user-vote-history)

```twig
{% set history = craft.upvote.userHistory() %}
```

Once you have the `history`, just check to see if the element's ID appears as a key in that array.

```json
{
    "14":  1,
    "33":  1,
    "39": -1,
    "42":  1
}
```

If you are also trying to match against a [unique key](https://www.doublesecretagency.com/plugins/upvote/docs/multiple-voting-for-the-same-element), then the array key may exist as a combined string...

```json
{
    "14:comfortable":  1,
    "14:clean":  1,
    "14:friendlyStaff":  -1
}
```

Using this approach, you should be able to recreate a wishlist functionality. I agree that it could benefit from a few additional helper methods... I have some long-term plans which will eventually make it even easier. 🙂

Hope that helps!

**Comment by lindseydiloreto** [comment]
There is a new `userVote` method in `v2.2` which addresses this nicely. You can now do this...

```twig
{% if 1 == craft.upvote.userVote(currentUser.id, entry.id) %}
    {# User has upvoted this entry #}
{% endif %}
```

The `userVote` method allows you to retrieve a single, specific vote. "How did this user vote on this element?"

It returns one of the following values, based on how the user has (or hasn't) voted...

```
 1 = User has cast an upvote
-1 = User has cast a downvote
 0 = User has not voted on this element
```

You can (of course) specify a key as well, as the third parameter...

https://www.doublesecretagency.com/plugins/upvote/docs/user-vote-history

Thanks for the FR! 🙂
