### ISSUE TITLE
Can't display just the vote tally without including the upvote and downvote twig tags

### ISSUE THREAD

**Issue by tom-byrom** [doublesecretagency/craft-upvote#23]
Hi,
If I just want to display the total number of votes for an entry in a list of entries, currently it won't display a number unless  I include the upvote and downvote twig tags as well

If I just use the below in a for each loop
`{{ craft.upvote.tally(entry.id) }}`  

It doesn't display any number and when i inspect it just has:
`<span data-id="30" class="upvote-el upvote-tally upvote-tally-30">&nbsp;</span>`

But if I add the other 2 tags to allow upvoting and downvoting the correct number displays?

Why is this? I have a front end entries feed where I just want to display the total number and only allow voting on the entry it self.

Thanks

**Comment by lindseydiloreto** [comment]
Hi Tom,

Looks like you've discovered a minor bug! Thanks for reporting it. 👍

Fortunately, there's a very easy workaround...

```twig
{{ craft.upvote.tally(entry.id, null, 'number') }}
```

https://www.doublesecretagency.com/plugins/upvote/docs/control-the-output-format

Let me know if that does the trick!

**Comment by tom-byrom** [comment]
Hi @lindseydiloreto 

Yep that seems to do the trick. Thanks!

**Comment by lindseydiloreto** [comment]
Just FYI, this has been fixed in Upvote **2.2**, released today! 🎉

You no longer need to use the workaround. Thanks again for reporting it!
