### ISSUE TITLE
How to display a list of entries you've voted on?

### ISSUE THREAD

**Issue by tom-byrom** [doublesecretagency/craft-upvote#24]
I'm using the below code to get the currently logged in member's vote history and trying to return a list of entries they have voted on.

```
{% set memberHistory = craft.upvote.userHistory() %}
<ul>
{% for entry in memberHistory %}
<li>{{ entry.title }}</li>
{% endfor %}
</ul>
```

But I keep getting this error

`Impossible to access an attribute ("title") on a integer variable ("1").`

How would I go about getting data from the entries that they have cast a vote on? Such as title links etc. 

I can't work it out from the docs

Thanks

**Comment by lindseydiloreto** [comment]
Hi Tom,

Take a look at the **History Format** section of this page...

https://www.doublesecretagency.com/plugins/upvote/docs/user-vote-history

![history-format@2x](https://user-images.githubusercontent.com/5309692/84697566-3a885f80-af03-11ea-9a0d-20c93f644425.png)

Sorry if that's unclear. Essentially, each **key** of this array is simply the **element ID** of whichever item was voted on. The **value** of each item is just the direction of each vote (`1` is an upvote, `-1` is a downvote).

```js
{
    14:  1  // <---- Upvote on element 14
    39: -1  // <---- Downvote on element 39
}
```

You'll need to use the element IDs to look up each corresponding element. However you choose to do that is up to you.

One minor caveat... If you are using unique keys to achieve [multiple voting for the same element](https://www.doublesecretagency.com/plugins/upvote/docs/multiple-voting-for-the-same-element), the user history array will be shaped a little differently...

```js
{
   "33:comfortable":  1
   "33:clean":  1
   "33:friendlyStaff":  -1
}
```

Hope that helps! 🙂

**Comment by tom-byrom** [comment]
Hi Lindsey,
I did read the docs but I still can't seem to do what I need from reading the above, sorry!

How do I get information related to the element Id out of this array? In my instance the element is an entry. My example is I want to display a list of liked posts on the front end that the user has liked.

Any chance you can point me in the right direction if the above makes sense?

Cheers
Tom

**Comment by tom-byrom** [comment]
@lindseydiloreto 
I think I've worked out a way to do what I want. It outputs the info I need.

What do you think? Is there a better way of achieving this? Or do you think this is ok?

```
<h2>Liked Entries</h2>

    {% set memberHistory = craft.upvote.userHistory() %}

    <ul>
    {% for key, value in memberHistory %}
         
        {% set entryId = key %}

        {% set myEntryQuery = craft.entries()
            .section('projects')
            .id(entryId)
             %}
        
        {% set entries = myEntryQuery %}

        {% for entry in entries %}

        <li>{{ entry.title }}</li>

        {% endfor %}

    {% endfor %}
    </ul>
```

**Comment by lindseydiloreto** [comment]
Looks like you're one step ahead of me, I was just about to post these examples... 🙂

```twig
<ul>
    {% for id,vote in craft.upvote.userHistory() %}
        {% set entry = craft.entries.id(id).one() %}
        {% if entry %}
            <li>{{ entry.title }}</li>
        {% endif %}
    {% endfor %}
</ul>
```

For the record, _this first example is not very performant_... It is making a separate `craft.entries` call on each iteration of the loop. This first example is just the most straightforward example to give you an idea of how to approach it.

If you want to approach it with some level of performance in mind, I'd recommend aggregating the **keys** of the user history data, and passing that into the entries query as an array.

```twig
{% set entryIds = craft.upvote.userHistory()|keys %}
{% set entries = craft.entries.id(entryIds).all() %}
```

^ Your logic could be as simple as this second example _**only if...**_
- You are not using [multiple voting](https://www.doublesecretagency.com/plugins/upvote/docs/multiple-voting-for-the-same-element), which would make your keys harder to work with,
- And you are not allowing downvotes (`-1`), which would give you false positives.

If either of those statements isn't true, you'll need to find some hybrid approach which addresses your complications, while trying to remain performant.

**Comment by tom-byrom** [comment]
@lindseydiloreto you're awesome thanks for this. 

I've gone with the performance one as my use case fits perfectly.

So I ended up with

`
<ul>
         
        {% set entryIds = craft.upvote.userHistory()|keys %}
        {% set entries = craft.entries.id(entryIds).all() %}

        {% for entry in entries %}

        <li>
            <div>{{ craft.upvote.upvote(entry.id) }}</div>
            <div>{{ craft.upvote.tally(entry.id) }}</div> <a href="{{ entry.url }}">{{ entry.title }}</a>
        </li>

        {% endfor %}

    </ul>
`
Really appreciate the help on this one :)

**Comment by lindseydiloreto** [comment]
Ok excellent! That looks perfect.

No problem at all, glad you got it all sorted out! 👍
