### ISSUE TITLE
Viewing vote data in control panel

### ISSUE THREAD

**Issue by samdking** [doublesecretagency/craft-upvote#27]
Is it currently possible to view this data in the control panel anywhere? A report page would be nice (showing most and least popular entries, for example).

I gather this is probably quote a bespoke requirement depending on your implementation.

I'm using this plugin as an "anonymous" up/down vote on the front-end for users, and would like to make the vote tallies available for admins only, in the control panel. Would you suggest making a custom page only viewable in the control panel for this?

**Comment by lindseydiloreto** [comment]
Hi @samdking,

It's kind of buried in the docs, but you should be able to add that info as a **column** on your entries index page...

<img width="676" alt="index@2x" src="https://user-images.githubusercontent.com/5309692/92512196-48c4df80-f1c3-11ea-89e0-2304841371f0.png">

Hope that helps!

**Comment by samdking** [comment]
Thank you! I saw that article but didn't clock that you could just add those columns to an index page. That's perfect!
