### ISSUE TITLE
Add Scripts from cpresources Folder over Enviroments

### ISSUE THREAD

**Issue by davidhellmann** [doublesecretagency/craft-upvote#29]
Hey,

when I add the js files like this: 
```
<script src="{{ rootUrl }}cpresources/c0af6e70/js/sizzle.js?v=1604533199"></script>
<script src="{{ rootUrl }}cpresources/c0af6e70/js/superagent.js?v=1604533199"></script>
<script src="{{ rootUrl }}cpresources/c0af6e70/js/upvote.js?v=1604533199"></script>
```

I've the problem that the hashes are different from my local to my live env. 
Is the one and only option to get the files from the vendor folder?

**Comment by lindseydiloreto** [comment]
Yes, I believe that's the only way (at this time). You could create an alias or environmental variable to reference different folder names in different environments.

**Comment by lindseydiloreto** [comment]
Untested, but see if you can just register the Asset Bundle via Twig...

```twig
{% do view.registerAssetBundle('doublesecretagency\\upvote\\web\\assets\\JsAssets') %}
```
