### ISSUE TITLE
Unable to remove a vote via AJAX

### ISSUE THREAD

**Issue by johndwells** [doublesecretagency/craft-upvote#30]
I am submitting an AJAX POST request to the `upvote/vote/remove`, sending CSRF token & element ID, but the response I get back is:

> Unable to remove vote. No vote was ever cast.

But, the current user has voted for the element.

In the case of voting & removing, I'm not setting a key. But even if I do set a key, the result is the same.

Upvote: 2.2.1
Craft CMS: 3.5.17.1

**Comment by lindseydiloreto** [comment]
After a private chat, this was traced back to a conflict in a custom module. Glad you got it sorted! 👍
