### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by kevadamson** [doublesecretagency/craft-upvote#31]
Does `{% do craft.upvote.sort(list) %}` work on paginated entries?

I get this error: `Argument 1 passed to doublesecretagency\upvote\variables\UpvoteVariable::sort() must be an instance of craft\elements\db\ElementQuery, array given, called in /home/foo/vendor/twig/twig/src/Extension/CoreExtension.php on line 1511` when trying.

**Comment by lindseydiloreto** [comment]
I'm guessing that the `list` variable has already been processed with `.all()`.

Would you mind checking how the `list` variable is being set?

**Comment by kevadamson** [comment]
Yes sorry. I didn't really give you enough details.

`{% paginate craft.entries.section('advice').relatedTo(null).search('').orderBy('postDate desc').limit('10') as list %}`

`relatedTo`, `search`, `orderBy` and `limit` are all dynamic by the way - I've just put those values in as a default example from values in parameters / segments.

**Comment by lindseydiloreto** [comment]
Ah yes, so you'd probably want something more like this...

```twig
{# Get all entries #}
{% set allEntries = craft.entries
    .section('advice')
    .relatedTo(null)
    .search('')
    .orderBy('postDate desc')
    .limit(10) %}

{# Sort by highest voted #}
{% do craft.upvote.sort(allEntries) %}

{# Apply pagination #}
{% paginate allEntries as list %}
```

It's kind of described [here](https://plugins.doublesecretagency.com/upvote/sort-by-highest-voted/), although the docs don't explicitly mention pagination...

<img width="762" alt="Element Query@2x" src="https://user-images.githubusercontent.com/5309692/121388680-86949700-c900-11eb-806b-2e6aa877f83d.png">

Much like `.all()`, pagination will convert the Element Query into an array. The sorting for Upvote must be done on the raw Element Query, before it's been converted to an array.

Hope that helps! 🙂

**Comment by kevadamson** [comment]
Oh gosh yes that does make sense. Thanks for walking me through it :)
