### ISSUE TITLE
allow user to be able to vote from anew each time. 

### ISSUE THREAD

**Issue by vasuhooda** [doublesecretagency/craft-upvote#32]
Is it possible to use the plugin without cookies? 

We want the user to be able to vote from anew each time.

**Comment by lindseydiloreto** [comment]
Hi there. What exactly do you mean by "each time"?

What if someone repeatedly refreshes the browser? Would they be able to vote again every time they refresh?

**Comment by vasuhooda** [comment]
By each time I mean each session. Yes, they would be able to vote again every time they refresh

**Comment by lindseydiloreto** [comment]
That seems like a recipe for massive voter fraud. Not sure why you would want to open up a loophole that big.

It isn't currently configurable, but you can fork the plugin and change the `userCookieLifespan` to be `0`...

https://github.com/doublesecretagency/craft-upvote/blob/aa81bc70fc19863bd4a2524cf462542c5f1fbcac/src/services/UpvoteService.php#L31
