### ISSUE TITLE
Return only entries that have been voted on

### ISSUE THREAD

**Issue by jeffaglenn** [doublesecretagency/craft-upvote#6]
I have "favorites" set up and working great for users. Now I'm trying to add a "Most Favorited" section on a page out of all entries in a section ( e.g. styles). I was trying to return the entires based on if `craft.upvote.tally(id)` was greater than 0 but I'm seeing that it is spitting out a `span` with classes rather than an integer.

Current code (I think I'm over simplifying):
```twig
{% set styles = craft.entries.section('styles') %}
{% do craft.upvote.sort(styles) %}

{% for favoriteStyle in styles %}
    {% if craft.upvote.tally(favoriteStyle.id) > 0 %}

        {{ favoriteStyle.title }}
        {{ craft.upvote.tally(favoriteStyle.id) }}

    {% endif %}
{% endfor %}
```
Of course, this throws errors. Any thoughts?

**Comment by jeffaglenn** [comment]
Since I'm only doing Up Votes looks like I needed to change `craft.upvote.tally` to `craft.upvote.totalVotes` in my `if` statement. That will only return an element if it has a vote greater than `0`.

**Comment by lindseydiloreto** [comment]
Hey Jeff, sorry I never responded!

Yes, your solution should work. For future reference, you could do it with the Twig [striptags](https://twig.symfony.com/doc/2.x/filters/striptags.html) filter as well...

```twig
{% set tally = craft.upvote.tally(favoriteStyle.id) | striptags %}
```

That will remove the HTML tags and make the tally numeric.
